name: OKEJSPACE-SKYGENGENERATORS
version: '${project.version}'
main: pl.okej.okejspaceskygengenerators.Main
api-version: '1.18'
depend: [Vault]
authors: [ok_ej]
description: Plugin na generatory skygen wzorowany na serwerze MINESTAR.PL
  
commands:
  okejgenerators:
    description: Główna komenda do pluginu
    usage: |-
      /<command> reload - Reload configuration
      /<command> genboost <ilość> <czas> - Activate generator boost
      /<command> nadaj <nazwa> - Give genboost item
      /<command> toggle <generator> - Toggle generator on/off
      /<command> list - List all generators
    aliases: [skyg, generators, okejgenerators, okgen]
    permission: okejgenerators.admin

permissions:
  okejgenerators.admin:
    description: Allows access to admin commands
    default: op
  okejgenerators.collect:
    description: Allows collecting money from generators
    default: true
  okejgenerators.genboost:
    description: Allows using genboost items
    default: true